AWSTemplateFormatVersion: 2010-09-09
Description: Voice Crawler Template
Parameters:
  RawAudioBucketName:
    Type: String
    Description: S3 Bucket name for raw audio files
    Default: raw-audio-voice-crawler
  TranscribedAudioBucketName:
    Type: String
    Description: S3 Bucket name for transcribed audio files
    Default: transcribed-audio-voice-crawler

Resources:
  RawAudioS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RawAudioBucketName
  TranscribedAudioBucketName:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TranscribedAudioBucketName
